Cost validator
crypto-pepe/firewall-analyzer pull request #10
Opened 2022-06-14 13:22 UTC by horny-manul

2022-06-15 08:24 UTC, stuffy-idler requested changes

2022-06-16 09:06 UTC, stuffy-idler requested changes

2022-06-16 09:06 UTC, stuffy-idler commented on src/validators/requests_from_ip_cost/validator.rs
> +    fn validate(&mut self, req: Request) -> Result<Option<BanRequest>, Error> {
Should be refactored: too many returns, not obvious if-else statements, not obvious `0` usage (`let rule = self.rules.get(0)`, `state.applied_rule_idx = Some(0);`, `let rule = self.rules[0];`), naming

2022-06-16 09:06 UTC, stuffy-idler commented on src/validators/requests_from_ip_cost/validator.rs
> +fn apply_rule_if_possible(
I suggest to inject it to the code – it is used only once, it mutate the state, it fetches the rule from rules and then rule is fetched again in case of rule application

2022-06-17 09:23 UTC, citizensix commented on src/validators/requests_from_ip_cost/validator.rs
> +        };
`.map_or_else()`

2022-06-17 09:24 UTC, citizensix commented on src/validators/requests_from_ip_cost/validator.rs
> +    fn validate(&mut self, req: Request) -> Result<Option<BanRequest>, Error> {
++

2022-06-17 16:23 UTC, stuffy-idler requested changes

2022-06-17 16:23 UTC, stuffy-idler commented on src/validators/requests_from_ip_cost/validator.rs
> +        // Whether target is not banned
I guess it is located in wrong place, `should_reset_timeout` does not check whether target is banned or not

2022-06-17 16:23 UTC, stuffy-idler commented on src/validators/requests_from_ip_cost/validator.rs
> +            Some(applied_rule) => {
If some rule was applied, new requests from the target should not be handled? It does not added to recent requests

2022-06-20 08:28 UTC, horny-manul commented on src/validators/requests_from_ip_cost/validator.rs
> +            Some(applied_rule) => {
If I remember correctly, if ban was applied and reset duration is still not exceeded, then total cost should be calculated from ban beginning till reset duration end.

2022-06-20 08:29 UTC, horny-manul commented on src/validators/requests_from_ip_cost/validator.rs
> +            Some(applied_rule) => {
So it is not reqired to store time of requests, only total cost

2022-06-20 09:46 UTC, merged