4 retry for forwarder
crypto-pepe/firewall-analyzer pull request #11
Opened 2022-06-15 13:47 UTC by horny-manul

2022-06-15 14:05 UTC, citizensix commented on src/forwarder/service.rs
> +                    if let Err(e) = ban_result {
Double-checking an error. Consider extracting error instead of calling `.is_err()`

2022-06-16 09:50 UTC, stuffy-idler requested changes

2022-06-16 09:50 UTC, stuffy-idler commented on config.yaml
> +forwarder_http_client:
It is excess to bring the implementation details out, user should not know whether there is http client with service or something else. So I suggest to define single config section `forwarder` and keep all its settings there

2022-06-16 09:50 UTC, stuffy-idler commented on config.yaml
> +  analyzer_name: "analyzer-1"
It used by forwarder, but it is implementation details. I suggest to define this parameter separately (or in `app` config section)

2022-06-16 09:50 UTC, stuffy-idler commented on src/forwarder/service.rs
> +    retry_strategy: Take<FixedInterval>,
What it the reason to keep it as `Take` iterator, why not just a `FixedInterval`?

2022-06-16 09:50 UTC, stuffy-idler commented on src/forwarder/service.rs
> +                        for wait in self.retry_strategy.clone() {
Why you don't use `tokio_retry::Retry`?

2022-06-16 15:14 UTC, horny-manul commented on src/forwarder/service.rs
> +                        for wait in self.retry_strategy.clone() {
It can't be done because of `await`, it can't be used inside closure

2022-06-16 17:12 UTC, stuffy-idler commented on src/forwarder/service.rs
> +                        for wait in self.retry_strategy.clone() {
It seems to work:
```rust
let result = tokio_retry::Retry::spawn(self.retry_strategy.clone(), || {
    self.client.ban(validator_ban_request.ban_request.clone(), analyzer_id.clone())
  })
  .await;
if let Err(e) = result {
  // error handler              
}
Ok(())
```

2022-06-16 17:16 UTC, stuffy-idler requested changes

2022-06-16 17:16 UTC, stuffy-idler commented on config.yaml
>  analyzer_name: "analyzer-1"
IMO, It's looks weird `name` of `analyzer`. Actually the purpose of this parameter is to identify analyzer instance, so maybe name it `analyzer_id` or just `id`?

2022-06-17 08:58 UTC, horny-manul commented on src/forwarder/service.rs
> +                        for wait in self.retry_strategy.clone() {
I was using it incorrectly 😞. Fixed

2022-06-17 15:09 UTC, stuffy-idler requested changes

2022-06-17 15:09 UTC, stuffy-idler commented on src/forwarder/service.rs
> +    retry_strategy: Take<tokio_retry::strategy::FixedInterval>,
What is the reason to use `Take<_>`?

2022-06-17 15:09 UTC, stuffy-idler commented on src/forwarder/service.rs
>      client: Box<dyn ExecutorClient + Send + Sync>,
I suggest it to name accordingly to it purpose – `executor_client` or simply `executor`.
For now it looks like
```rust
let int = 10;
```

2022-06-17 15:09 UTC, stuffy-idler commented on src/forwarder/service.rs
> +            analyzer_id: analyzer_name,
Use consistent naming

2022-06-17 15:09 UTC, stuffy-idler commented on src/forwarder/service.rs
>                          tracing::error!("{:?}", e)
Maybe it should panic in case when ban request failed after all attempts?

2022-06-17 15:09 UTC, stuffy-idler commented on config.yaml
> +  retry_wait: 3s
`_wait` is not prompt that this is duration. I suggest to name it more obvious, `retry_interval` or smth similar

2022-06-17 15:21 UTC, horny-manul commented on src/forwarder/service.rs
> +    retry_strategy: Take<FixedInterval>,
Because `FixedInterval` yields duration infinite times. Without `Take` it is required to have `retry_count` field in `Service`

2022-06-17 15:22 UTC, horny-manul commented on src/forwarder/service.rs
> +    retry_strategy: Take<tokio_retry::strategy::FixedInterval>,
Because `FixedInterval` yields duration infinite times. Without `Take` it is required to have `retry_count` field in `Service`

2022-06-17 15:36 UTC, stuffy-idler commented on src/forwarder/service.rs
> +    retry_strategy: Take<tokio_retry::strategy::FixedInterval>,
Got it. Ok

2022-06-20 10:42 UTC, stuffy-idler commented on src/forwarder/service.rs
>                          tracing::error!("{:?}", e)
I agree

2022-06-20 10:42 UTC, stuffy-idler approved these changes

2022-06-20 11:03 UTC, merged