Analyzer
crypto-pepe/firewall-analyzer pull request #5
Opened 2022-05-24 10:28 UTC by hehegrrrhehegrr

Closes #3

2022-05-30 10:58 UTC, stuffy-idler requested changes

2022-05-30 10:58 UTC, stuffy-idler commented on src/receiver/service.rs
> +            for ms in mss.iter() {
Can it be rewritten in FP way?

2022-05-30 10:58 UTC, stuffy-idler commented on src/validator/mod.rs
> +    Dummy {
I suggest to define `DummyConfig` at `dummy.rs` and use it here as `Dummy(DummyConfig)`

2022-05-30 10:58 UTC, stuffy-idler commented on src/validator/mod.rs
> +        Dummy { idx, ban_ttl } => {
If `Dummy` will contain `DummyConfig` (`Dummy(c)`), `DummyValidator` initialisation can be rewritten as `DummyValidator::new(c)`. Therefore all of its initialisation details can be placed and hidden there

2022-05-30 10:58 UTC, stuffy-idler commented on src/validator/service.rs
> +                        return;
Let return an `Err`, not just breaking the loop. Error handling should be done on the highest level

2022-05-30 10:58 UTC, stuffy-idler commented on src/validator/service.rs
> +                            if let Err(e) = send.send(s).await {
I guess if ban request sending failed with an error, something wrong occurred with the channel, therefore it's better to break the loop and return an error to the highest level. Otherwise consequent ban requests will also fail and bans will not be executed

2022-05-30 10:58 UTC, stuffy-idler commented on src/forwarder/service.rs
> +                // todo maybe blocking receive and inside of select?
What is the reason to do this?

2022-05-30 10:58 UTC, stuffy-idler commented on src/forwarder/service.rs
> +    c: Box<dyn ExecutorClient + Send + Sync>,
Let's name it `client` at least. `c` is not descriptive variable name at all

2022-05-30 10:58 UTC, stuffy-idler commented on src/main.rs
> +    tokio::spawn(async move { fw.run(fr).await });
Add handler for task join handle

2022-05-30 10:58 UTC, stuffy-idler commented on src/main.rs
> +    tokio::spawn(async move { krs.run(s).await });
Add handler for task join handle

2022-06-01 12:52 UTC, stuffy-idler requested changes

2022-06-02 11:19 UTC, stuffy-idler requested changes

2022-06-02 11:19 UTC, stuffy-idler commented on src/main.rs
> +        _ = request_consumer_handle => (),
Please add appropriate log messages (info or error) that the task was finished and in case of error – print the error

2022-06-02 11:19 UTC, stuffy-idler commented on src/forwarder/noop_client.rs
> +        tracing::warn!("dry run mod");
Mistype `mode`

2022-06-02 16:14 UTC, stuffy-idler requested changes

2022-06-02 16:14 UTC, stuffy-idler commented on src/validator/service.rs
> +            if let Err(e) = join_all(handles).await.into_iter().try_for_each(|r| r) {
`try_for_each` here looks like hack. Better to use `collect`: `.collect::<Result<(), _>>()`

2022-06-02 16:14 UTC, stuffy-idler commented on src/forwarder/http_client.rs
> +            .map_err(|e| ForwarderError::NewForwarder(e.to_string()))?;
I suggest to rename it to `BuildForwarder`, `NewForwarder` does not sounds obviously

2022-06-02 16:14 UTC, stuffy-idler commented on readme.md
> +## Writing your own validator
Need to be actualised

2022-06-02 16:14 UTC, stuffy-idler commented on Cargo.toml
> +openssl = { version = "0.10", features = ["vendored"] }
What is it for?

2022-06-02 16:14 UTC, stuffy-idler commented on Cargo.toml
> +bincode = "1.3.3"
What is it for?

2022-06-02 16:14 UTC, stuffy-idler commented on Cargo.toml
> +firewall-executor = { git = "https://github.com/crypto-pepe/firewall-executor", branch = "develop" }
Is it used?

2022-06-06 11:32 UTC, citizensix commented on src/consumer/mod.rs
> +    async fn run(&mut self, out: mpsc::Sender<Request>) -> Result<(), anyhow::Error>;
You can use ```Result``` from ```anyhow``` crate to simply return ```Result<()>```

2022-06-06 11:32 UTC, citizensix commented on src/consumer/service.rs
> +        Ok(KafkaRequestConsumer { c })
```Ok(Self{...})```?

2022-06-06 11:32 UTC, citizensix commented on src/consumer/service.rs
> +    async fn run(&mut self, out: mpsc::Sender<Request>) -> Result<(), anyhow::Error> {
`use anyhow::Result`
```
...
async fn run(&mut self, out: mpsc::Sender<Request>) -> Result<()>
```

2022-06-06 11:32 UTC, citizensix commented on src/consumer/service.rs
> +            };
You can use `or_else()` to do something with error instead of matching pattern
```let mss = match consumer.lock().await.poll().or_else(...)```?

2022-06-06 11:32 UTC, citizensix commented on src/forwarder/error.rs
> +    #[error("status code '{0:?}'; body = {1:?}")]
if you want to log just the code – use `.to_u16()`

2022-06-06 11:32 UTC, citizensix commented on src/forwarder/http_client.rs
> +        })
Consider using `Self` value

2022-06-06 11:32 UTC, citizensix commented on src/forwarder/service.rs
> +        Service { client: c }
Consider using `Self` value

2022-06-06 11:32 UTC, citizensix commented on src/forwarder/service.rs
> +                    }
The common way to handle an error is using `map_err` and `?`

2022-06-06 11:32 UTC, citizensix commented on src/main.rs
> +            }
Consider using `map_or_else()` or smth similar

2022-06-06 11:32 UTC, citizensix commented on src/validator/dummy.rs
> +}
Instructions unclear: idx * mintutes or seconds according to Dummy struct field?

2022-06-06 11:32 UTC, citizensix commented on src/validator/dummy.rs
> +    fn validate(&self, req: Request) -> Result<Option<model::BanRequest>, anyhow::Error> {
Consider using `anyhow::Result`

2022-06-06 11:32 UTC, citizensix commented on src/validator/mod.rs
> +    fn validate(&self, req: Request) -> Result<Option<model::BanRequest>, anyhow::Error>;
Consider using `anyhow::Result`

2022-06-06 11:32 UTC, citizensix commented on src/validator/service.rs
> +            };
Consider mapping error values

2022-06-06 11:32 UTC, citizensix commented on src/validator/service.rs
> +            };
The common way to handle an error is using map_err and ?

2022-06-06 11:54 UTC, horny-manul commented on src/forwarder/service.rs
> +                    }
Would be to complicated because of await - it can't be used inside closures

2022-06-07 10:38 UTC, stuffy-idler requested changes

2022-06-07 10:38 UTC, stuffy-idler commented on src/main.rs
> +    let fw: Box<dyn ExecutorClient + Send + Sync> = if cfg.dry_run {
I suggest to name it `executor_client`, because of it is used appropriately, it's not forwarder as is

2022-06-08 07:43 UTC, stuffy-idler requested changes

2022-06-08 07:43 UTC, stuffy-idler commented on src/main.rs
> +mod validator;
I think it will be better to rename this service to `provider` or `validation_provider` – it uses set of concrete validators under-the-hood but not doing validation as is, but just providing the incoming data to the underlying layer

2022-06-08 13:29 UTC, stuffy-idler requested changes

2022-06-09 08:34 UTC, stuffy-idler commented
@citizensix please review PR

2022-06-09 09:52 UTC, stuffy-idler requested changes

2022-06-09 10:00 UTC, horny-manul commented on src/validation_provider/dummy.rs
> +                    .unwrap_or_else(|| DurationString::from(Duration::from_secs(120)))
Can't do it because it expects DurationString

2022-06-09 10:38 UTC, stuffy-idler commented on src/validation_provider/dummy.rs
> +                    .unwrap_or_else(|| DurationString::from(Duration::from_secs(120)))
Got it, ok

2022-06-09 10:44 UTC, citizensix commented on src/forwarder/http_client.rs
> +        })
?

2022-06-09 11:02 UTC, citizensix requested changes
Also please check with clippy

2022-06-09 11:10 UTC, horny-manul commented on src/validation_provider/mod.rs
> +    fn name(&self) -> String;
Validator must have name, as it will be sent to executor

2022-06-09 11:22 UTC, horny-manul commented on src/validation_provider/service.rs
> +            let handles = self.validators.iter_mut().filter_map(|v| {
It's handle, not handler

2022-06-09 13:24 UTC, stuffy-idler requested changes

2022-06-09 13:46 UTC, horny-manul commented on src/validation_provider/dummy.rs
> +                analyzer: self.name(),
Now it is used in analyzer

2022-06-09 13:46 UTC, horny-manul commented on src/validation_provider/requests_from_ip_counter/validator.rs
> +            analyzer: self.name(),
No more analyzer field in this struct

2022-06-09 13:47 UTC, horny-manul commented on src/validation_provider/requests_from_ip_counter/validator.rs
> +    }
Now this method is used outside validator pkg

2022-06-09 15:11 UTC, stuffy-idler requested changes

2022-06-09 15:11 UTC, stuffy-idler commented on src/model/mod.rs
> +pub struct ValidatorBanRequest {
I suggest to name it `BanRequest`...

2022-06-09 15:11 UTC, stuffy-idler commented on src/model/mod.rs
> +pub struct BanRequest {
and this name `ValidatorBanRequest` with fields `ban_request` and `validator_name`

2022-06-09 15:11 UTC, stuffy-idler commented on src/forwarder/mod.rs
> +    async fn ban(&self, br: BanRequest) -> Result<(), ForwarderError>;
Executor requires analyzer-id for `ban` endpoint – I suggest to make it as separated argument and not to mix it with `BanRequest`. In this way you would use it at:
```rust
match recv.try_recv() {
  Ok(validator_ban_request) => {
    let analyzer_id = format!("{}:{}", self.analyzer_name, validator_ban_request.validator);
    if let Err(e) = self.client.ban(analyzer_id, validator_ban_request.ban_request).await {
      // ..
    }
  }
}
```

2022-06-09 15:28 UTC, horny-manul commented on src/validators/requests_from_ip_counter/validator.rs
> +use crate::validators::requests_from_ip_counter::error::RulesError::NotFound;
Because `RulesError` is return type of functions there I removed `RulesError::NotFound` instead

2022-06-09 15:29 UTC, horny-manul commented on src/validation_provider/service.rs
> +                            println!("{}", serde_json::to_string(&ban_request).unwrap());
Forgot to remove when tested

2022-06-10 08:50 UTC, stuffy-idler commented on src/validators/requests_from_ip_counter/validator.rs
> +use crate::validators::requests_from_ip_counter::error::RulesError::NotFound;
That's what I wanted to suggest :) 

Common way to use enumeration is to import entire `enum` and specify it concrete case at each of necessary sites

2022-06-10 08:55 UTC, stuffy-idler requested changes

2022-06-10 08:55 UTC, stuffy-idler commented on src/model/mod.rs
> +    #[serde(flatten)]
Is it necessary?

2022-06-10 08:55 UTC, stuffy-idler commented on src/model/mod.rs
> +    #[serde(skip_serializing)]
Is it necessary?

2022-06-10 09:26 UTC, citizensix requested changes

2022-06-10 09:26 UTC, citizensix commented on Cargo.toml
> +edition = "2021"
Wish we could go back in time 🥲

2022-06-10 09:26 UTC, citizensix commented on src/consumer/mod.rs
> +}
```suggestion
use crate::model::Request;
use anyhow::Result;

pub use self::service::KafkaRequestConsumer;

mod service;

#[async_trait]
pub trait RequestConsumer {
    async fn run(&mut self, out: mpsc::Sender<Request>) -> Result<()>;
}
```

2022-06-10 09:26 UTC, citizensix commented on src/forwarder/http_client.rs
> +        })
Still unchanged

2022-06-10 09:26 UTC, citizensix commented on src/telemetry/mod.rs
> +    }
```suggestion
    if cfg.jaeger_endpoint.is_some() {
        let ep = cfg.jaeger_endpoint.as_ref().unwrap();
        let tracer = init_tracer(cfg.svc_name.to_string(), ep.into());
        return Box::new(reg.with(tracing_opentelemetry::layer().with_tracer(tracer)));
    }
        Box::new(reg)
```

2022-06-10 09:26 UTC, citizensix commented on src/validators/requests_from_ip_counter/validator.rs
> +
Unnecessary newline

2022-06-10 09:26 UTC, citizensix commented on src/validators/requests_from_ip_counter/validator.rs
> +            if *state.recent_requests.iter().last().unwrap() <= now - rule.reset_duration {
I guess it's better to use smth like `Sub` on `UTC::DateTime`

2022-06-10 09:26 UTC, citizensix commented on src/validators/requests_from_ip_counter/validator.rs
> +            state.resets_at = Utc::now() + rule.reset_duration;
- You've declared `now` earlier
- Better to use `Add` method

2022-06-10 09:28 UTC, horny-manul commented on Cargo.toml
> +edition = "2021"
This is rust edition, 2022 is unsupported)

2022-06-10 09:36 UTC, horny-manul commented on src/validators/requests_from_ip_counter/validator.rs
> +            if *state.recent_requests.iter().last().unwrap() <= now - rule.reset_duration {
It is the same

2022-06-10 09:41 UTC, horny-manul commented on src/validators/requests_from_ip_counter/validator.rs
> +            state.resets_at = Utc::now() + rule.reset_duration;
> now 

Done

> add

https://doc.rust-lang.org/std/ops/trait.Add.html

2022-06-10 09:42 UTC, citizensix commented on src/validators/requests_from_ip_counter/validator.rs
> +            if *state.recent_requests.iter().last().unwrap() <= now - rule.reset_duration {
Yeah, they wrote it so you could not do it manually, it's always better to use pre-defined methods because it's more obvious and prettier

2022-06-10 09:44 UTC, citizensix commented on src/validators/requests_from_ip_counter/validator.rs
> +            state.resets_at = Utc::now() + rule.reset_duration;
See previous conversation

2022-06-10 09:51 UTC, citizensix approved these changes
LGTM

2022-06-10 10:04 UTC, stuffy-idler approved these changes

2022-06-10 10:06 UTC, merged