2 analyzer requests count from ip validator
crypto-pepe/firewall-analyzer pull request #7
Opened 2022-05-27 09:43 UTC by hehegrrrhehegrr

Closes #2

2022-05-31 17:13 UTC, stuffy-idler requested changes

2022-05-31 17:15 UTC, stuffy-idler commented
Please add description to readme for validator usage

2022-06-07 13:13 UTC, stuffy-idler requested changes

2022-06-07 13:13 UTC, stuffy-idler commented on src/validator/ip_count/validator.rs
> +            if *data.recent_requests.iter().last().unwrap() <= now - rule.reset_duration {
`last` will always return lastly pushed, therefore it always be equal to `now`.
Is it valid condition? Whether you want to take the oldest one?

2022-06-07 13:13 UTC, stuffy-idler commented on src/validator/ip_count/validator.rs
> +    fn ban(&self, rule_idx: usize, ip: String) -> BanRequest {
I suggest to take `ttl` as parameter instead of rule_idx – I guess it will be cleaner.

2022-06-07 13:13 UTC, stuffy-idler commented on src/validator/ip_count/validator.rs
> +        // No ban now
`Whether target is not banned`

2022-06-07 13:13 UTC, stuffy-idler commented on src/validator/ip_count/state.rs
> +    pub fn apply_rule_if_possible(
What is the reason to create this function as method for `State` struct, which does not know anything about rules? I suggest to move it to more suitable site

2022-06-07 13:13 UTC, stuffy-idler commented on src/validator/mod.rs
> +pub mod ip_count;
It's not only about ip count, but about counting requests from ip. I guess the name `requests_from_ip_counter` will be more descriptive

2022-06-07 16:16 UTC, horny-manul commented on src/validator/ip_count/validator.rs
> +            if *data.recent_requests.iter().last().unwrap() <= now - rule.reset_duration {
`last` in CircularQueue returns the earliest added element

2022-06-08 07:23 UTC, stuffy-idler commented on src/validator/ip_count/validator.rs
> +            if *data.recent_requests.iter().last().unwrap() <= now - rule.reset_duration {
My bad, you are right.

2022-06-08 07:38 UTC, stuffy-idler requested changes

2022-06-08 07:38 UTC, stuffy-idler commented on src/validator/mod.rs
> +    IpCount {
`IpCount` config should be extracted to appropriate validator according to `dummy::Config`

2022-06-08 07:38 UTC, stuffy-idler commented on src/validator/requests_from_ip_counter/validator.rs
> +pub struct IPCount {
Consider to renaming according to validator name `requests_from_ip_counter`

2022-06-08 07:38 UTC, stuffy-idler commented on src/validator/requests_from_ip_counter/validator.rs
> +fn apply_rule_if_possible(
Commonly in Rust tests are the last in the module file

2022-06-08 07:38 UTC, stuffy-idler commented on src/validator/requests_from_ip_counter/state.rs
> +    NoRules(usize),
I suggest to name it `RuleNotFound` as you described in the display text. `NoRules` means there are no any rules, it's not about missing rule

2022-06-08 15:58 UTC, stuffy-idler requested changes

2022-06-08 15:58 UTC, stuffy-idler commented on src/validator/mod.rs
> +    RequestsFromIPCount(requests_from_ip_counter::Config),
I suggest to name it according to validator – `RequestsFromIpCounter`

2022-06-09 09:25 UTC, stuffy-idler approved these changes

2022-06-09 09:27 UTC, merged